service: expenses
provider:
 name: aws
 runtime: python3.9
 stage: dev
 region: ap-northeast-1
 memorySize: 128
plugins:
 - serverless-wsgi
 - serverless-python-requirements
custom:
 wsgi:
   app: src.app.app
   packRequirements: false
functions:
 app:
   handler: wsgi_handler.handler
   events:
     - http: ANY /
     - http: 'ANY /{proxy+}'